# Generated by Django 4.0.6 on 2022-07-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='role',
            new_name='rolex',
        ),
    ]
