# Generated by Django 4.0.6 on 2022-07-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0002_rename_role_userrole_rolex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='rolex',
            new_name='role',
        ),
    ]
