# Generated by Django 4.0.6 on 2022-07-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0004_remove_userrole_user_userrole_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='role',
            new_name='description',
        ),
    ]
